name: The Flight Club
on:
  schedule:
    - cron: '00 00 * * 2'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r week-14/The-Flight-Club/requirements.txt

      - name: Run script
        env:
          
          SHEETY_USERNAME: ${{ secrets.SHEETY_USERNAME }}
          SHEETY_PASSWORD: ${{ secrets.SHEETY_PASSWORD }}
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python week-14/The-Flight-Club/main.py